### ISSUE TITLE
Is there a pre-trained model in the files?

### ISSUE THREAD

**Issue by JunshuaiFeng** [akaraspt/deepsleepnet#10]
I am currently referring this project for one of my ML classes and I heard it takes about one week to train the model, and I am still working on getting the MASS dataset. Was the trained model generated and saved somewhere in the files or I have to train it every time? It would be awesome if there is a pre-trained model, then I can maybe skip the training part to save some time for the predicting part.

Thanks in advance!

**Comment by akaraspt** [comment]
Thank you for your suggestions.

We have a plan to upload the pre-trained models, so that you can evaluate our model without training the model for all CV folds.

We will let you know once they have been uploaded.

**Comment by JunshuaiFeng** [comment]
Thank you very much!

**Comment by wusuowei11** [comment]
您好，现在预训练模型有上传么
