### ISSUE TITLE
Is ubuntu necessary? 

### ISSUE THREAD

**Issue by RAllon** [akaraspt/deepsleepnet#11]
Thank you so much for posting this repository. I have found it very helpful in further understanding deep learning. I have been trying to run your program. Is it possible to do so without downloading ubuntu?

**Comment by akaraspt** [comment]
This should be possible given that you can install all of the required Python package (in the correct version), but I haven't tried.

**Comment by RahulRagesh** [comment]
You can try Ubuntu Bash on Windows. Follow the link below to set it up.
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
