### ISSUE TITLE
Dependencies Details

### ISSUE THREAD

**Issue by balandongiv** [akaraspt/deepsleepnet#15]
Dear Akara,
Awesome work you have here.

Having gone through all the posted issue, really appreciate if you can add the detail version of the following dependencies. 

mne
matplotlib
scikit-learn
scipy
%%%%%%%
 Ubuntu 16.04
CUDA toolkit 8.0 and CuDNN v5
Python 2.7
tensorflow-gpu (0.12.1)
numpy (1.11.1) 
pandas (0.18.1)

I notice many report were mne-related issue (e.g., [here](https://github.com/akaraspt/deepsleepnet/issues/12), [here](https://github.com/akaraspt/deepsleepnet/issues/13))

Thanks in advance

**Comment by akaraspt** [comment]
I have committed the version from my virtual environment. Let me know if this does not work.

**Comment by akaraspt** [comment]
You can see from the README (I have updated it).
