### ISSUE TITLE
Question on the code

### ISSUE THREAD

**Issue by minho17** [akaraspt/deepsleepnet#16]
I have a question on the code 'predict.py'.

Why did you use custom_bidirectional_rnn in the 'predict.py'? What is difference between the custom_bidirectional_rnn and the bidirectional_rnn that is used in train?

If you give some comments, it will be very helpful to me. 

Thank you for reading my question.

**Comment by akaraspt** [comment]
Hi,

The custom_bidirectional_rnn was used to extract the LSTM cell values during the prediction to plot the figure shown in README.

**Comment by minho17** [comment]
Thank you for answering my question!
