### ISSUE TITLE
A wondering detail in your repository at the step of preparing dataset.

### ISSUE THREAD

**Issue by Stevewsw** [akaraspt/deepsleepnet#18]
hi 

when I prepared the dataset by your instruction, but something confused me.

`
cd data
chmod +x download_physionet.sh
./download_physionet.sh
`

### **error info:**

`
--2018-07-25 06:48:52--  https://www.physionet.oirg/physiobank/database/sleep-edfx/SC4001E0-PSG.edf
Resolving www.physionet.org (www.physionet.org)... 128.30.30.88
Connecting to www.physionet.org (www.physionet.org)|128.30.30.88|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-25 06:49:07 ERROR 404: Not Found.
`

### **I checked the file 'download_physionet.sh'.**

`
wang@wang:~/github/deepsleepnet-master/data$ head download_physionet.sh 
wget https://www.physionet.org/physiobank/database/sleep-edfx/SC4001E0-PSG.edf
wget https://www.physionet.org/physiobank/database/sleep-edfx/SC4001E0-PSG.edf.hyp
wget https://www.physionet.org/physiobank/database/sleep-edfx/SC4001EC-Hypnogram.edf
`

I open the first link : https://www.physionet.osrg/physiobank/database/sleep-edfx/SC4001E0-PSG.edf
It cannot be found, result as below:

`
The requested URL /physiobank/database/sleep-edfx/SC4001E0-PSG.edf was not found on this server.
`

_**So I just compared "the error link" with "the open source link":**_

No.1: wget https://www.physionet.org/physiobank/database/sleep-edfx/sleep-cassette/SC4001E0-PSG.edf
No.2: wget https://www.physionet.org/physiobank/database/sleep-edfx/SC4001E0-PSG.edf

**No.1 worked, because I can download it matually even but No.2 can't.**

So, my question is that _**if the link should be refreshed? and how about modifing your repository, refresh your file 'download_physionet.sh', into:**_

No.1: wget https://www.physionet.org/physiobank/database/sleep-edfx/sleep-cassette/xxx.edf
No.2: wget https://www.physionet.org/physiobank/database/sleep-edfx/xxx.edf

Just add "sleep-cassette/" after "sleep-edfx/".

It would be grateful if it would be responsed.

**Comment by akaraspt** [comment]
Thanks @Stevewsw. I have updated the link in `download_physionet.sh`
