### ISSUE TITLE
Can't read headers 

### ISSUE THREAD

**Issue by 3catz** [akaraspt/deepsleepnet#23]
When I try to read the headers for the PSG file 
I keep getting this error : 
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2110: character maps to <undefined>`

**Comment by akaraspt** [comment]
I think there might be some updates on other libraries.

Can you try to install python packages using the following version?

matplotlib (1.5.3)
scikit-learn (0.19.1)
scipy (1.0.0)
numpy (1.11.1)
pandas (0.18.1)
mne (0.15.2)
