### ISSUE TITLE
How to install tensorflow-gpu (0.12.1) in python 2.7?

### ISSUE THREAD

**Issue by lzr936332553** [akaraspt/deepsleepnet#24]
Hi akaraspt.I have some promble.Can you help me?My problem is error when I install tensorflow-gpu (0.12.1) in python 2.7.13 Error is as follow.

Could not find a version that satisfies the requirement tensorflow==0.12.1 (from versions: )
No matching distribution found for tensorflow==0.12.1
My command is pip install --upgrade tensorflow==0.12.1 .And tensorflow-gpu (0.12.1) is also error.

I can't understand why you can use it? Did you installed it by pip?
And I hava another question.Is CUDA toolkit 8.0 and CuDNN v5 necessary?

**Comment by akaraspt** [comment]
Please refer to solution suggested by 'nobar' in this [post](https://stackoverflow.com/questions/40416056/how-to-download-previous-version-of-tensorflow).

**Comment by lzr936332553** [comment]
Thanks for your answer .For the first I want run it in windows .So I have a question for this but now I have Ubantu to run your project .
    Very appreciate for your project .I just runing train.py and my computer is very slow .
    I want rewrite it by python 3 .If I can .And emmm thanks   ：）.I may have more silly questions for you in the future .haha.
