### ISSUE TITLE
If my collection point changes, does your code work?

### ISSUE THREAD

**Issue by lzr936332553** [akaraspt/deepsleepnet#26]
hi ，I come back again.：）
    I'm sorry to bother you . I just want to know can I use your code if my collection point is changed ?
    Just like your DS is fpz-cz I will change it to fp1-f4 . Does your code can work?
    Thanks for your reading .：）
    And I also have a question . I'm too lazy to try .Can you tell me if I use fpz-cz to train model but I use Pz-Oz'data to predict ？I guess that's not going to work, right ?

**Comment by akaraspt** [comment]
> Just like your DS is fpz-cz I will change it to fp1-f4 . Does your code can work?
As long as you have enough labels for fp1-f4 to train the model, it should be fine.

> Can you tell me if I use fpz-cz to train model but I use Pz-Oz'data to predict ？I guess that's not going to work, right ?
I would not work well compared to the signal from the same channel that the model has been trained on.

**Comment by lzr936332553** [comment]
Thank you so much .
