### ISSUE TITLE
can I use data which fs=512？

### ISSUE THREAD

**Issue by lzr936332553** [akaraspt/deepsleepnet#27]
I'm sorry to bother you again. As you can see can I use fs=512 data for direct staging? If I use your code and don't make any changes.Thanks for your reading in advance.: )

**Comment by akaraspt** [comment]
It should work fine given that your input signal has the sampling rate of 512Hz.

Please also make sure that your machine have enough space to support a larger network (by setting fs=512 will make the network larger).

**Comment by lzr936332553** [comment]
haha... I use my teacher's machine. It's powerful. But do you mean I need to retrain the model?And I have one more question .I predict that one fold is needed but I don't understand why 20 folds should be trained? I just made a summary of your project. I didn't really practice the latter.I'd appreciate it if you would explain it to me. Your previous answer helped me a lot. And make me learn more. Thank you so much .  ：）
