### ISSUE TITLE
 dataset

### ISSUE THREAD

**Issue by shenjianaixuexi** [akaraspt/deepsleepnet#33]
Dear akaraspt：
   Hello，I am working on sleep stages。I  have made some improvement on your code .But i can't get   
the MASSdataset.Can you give me some advice？
  Best regards!  
                                                                                                          Jianji  Zhang

**Comment by akaraspt** [comment]
You need to send a request to the authors of the dataset. Then they will advise you what are the documents you need to submit for access.

http://massdb.herokuapp.com/en/

**Comment by shenjianaixuexi** [comment]
Thank you for answering my letter so quickly.  I  will try  to get the dataset by the adress you provided.
THANK  YOU !
