### ISSUE TITLE
Problems to get hypnogram automatically scored by DeepSleepNet

### ISSUE THREAD

**Issue by DanloveFu** [akaraspt/deepsleepnet#40]
Hi, @genaris @akaraspt. Thanks for sharing your script.

But now, I can't find hypnogram automatically scored by DeepSleepNet when I run the whole code. However, you showed it in your literature like this.
![image](https://user-images.githubusercontent.com/58209378/119213289-9afb2600-baf0-11eb-8471-f6d4df65f416.png)

Did you add this drawing function to your code？Do you have any idea for this part? I am really appreciative of it.
Best wishes,

**Comment by akaraspt** [comment]
@DanloveFu I did not add this function in the code. This plot can be generated by plotting the output score from the model compared to the ground truth from the dataset.
