### ISSUE TITLE
Error in prepare_physionet

### ISSUE THREAD

**Issue by Denisolt** [akaraspt/deepsleepnet#5]
I have downloaded the EEG data using the script provided, when I run the command:
``` python prepare_physionet.py --data_dir data --output_dir data/eeg_fpz_cz --select_ch 'EEG Fpz-Cz' ``` it returns an error: ZeroDivisionError: float modulo
</br>
I tried to debug, and figuired that raw.ch is equal to 0 at the end. I think its because when it trimmes the tail, it trimmes the whole thing. 
Could you please help me understand what is wrong? thank you

**Comment by akaraspt** [comment]
Can you give me more details about the environment that you are using and the log of errors that you got?

**Comment by Denisolt** [comment]
Hey, I solved it. No worries. Thanks for a quick reply!

**Comment by silent567** [comment]
> Hey, I solved it. No worries. Thanks for a quick reply!

Hi, @Denisolt I have encounted the same problem. Could you please describe how you fix the bug?
