### ISSUE TITLE
how to extract many channel ?

### ISSUE THREAD

**Issue by shqing** [akaraspt/deepsleepnet#6]
Hi,
   if we want to extract many channel,  what should we do ? 
   python prepare_physionet.py --data_dir data --output_dir data/eeg_fpz_cz --select_ch 'EEG Fpz-Cz EOG  horizontal'   is wrong

**Comment by akaraspt** [comment]
Hi,

The current implementation of the `prepare_physionet.py` only support extracting **single-channel** EEG at the moment.

So running:
`python prepare_physionet.py --data_dir data --output_dir data/eeg_fpz_cz --select_ch 'EEG Fpz-Cz EOG horizontal'`
would not work.

The code I provided here is to reproduce the results mentioned in the paper, which only used single channel in the Physionet dataset.

You can modify my script in `prepare_physionet.py` to extract signals from more than one channel.

Hope this helps.

Akara
