### ISSUE TITLE
Train result differently when run from train_bash.sh with running directly form the train.py

### ISSUE THREAD

**Issue by joyicejin** [akaraspt/deepsleepnet#7]
when run the train.py directly  
the train result in fold0 (for example) directory tree is 
--fold0

   --deepfeaturenet
         --train_summary  (fold)
         --perf_fold0.npz
         --checkpoint
         --params_fold0.npz
         --perf_fold0.npz
         .........and so on
![image](https://user-images.githubusercontent.com/32789540/31852838-ce10f00c-b6b1-11e7-94ba-908be6db6789.png)

   --deepsleepnet
         --train_summary  (fold)
         --perf_fold0.npz
         --checkpoint
         --params_fold0.npz
         --perf_fold0.npz
         .........and so on

when use the argument:./batch_train.sh data/eeg_fpz_cz/ output 20 0 19 0
the train result in fold0 directory tree is 
--fold0
![image](https://user-images.githubusercontent.com/32789540/31852881-613ecf20-b6b2-11e7-82c0-03a55e675bbb.png)
   --deepfeaturenet (only has one fold)
        --train_summary
        --perf_fold0.npz

The difference is when the bash files result lack deepsleepnet fold and perf_fold0.npz
I just wonder why the result is different when use bash files. Could you help me?

**Comment by akaraspt** [comment]
Can you tell me more about the command that you use to run `train.py` directly?

**Comment by joyicejin** [comment]
My os is win10, 
so I changed the path in the train, and it can run smoothly using the .py directly
but I use the command batch_train.sh data\eeg_fpz_cz\ output 20 0 19 0, the error happens

**Comment by joyicejin** [comment]
Thanks for your comments, because of the bad command, solve it and closed
